apiVersion: v1
kind: Service
metadata:
  name: new-app-service
  labels:
    app: new-app 
spec:
  selector:
    app: new-app 
  ports:
    - protocol: TCP
      port: 80 # Porta que o Service expõe
      targetPort: 8000 # Porta do contêiner para onde o tráfego será direcionado
  type: NodePort # <--- Use NodePort para garantir que funcione em ambientes locais