apiVersion: apps/v1
kind: Deployment
metadata:
  name: newApp-deployment
  labels:
    app: newApp
spec:
  replicas: 1 # Apenas 1 réplica para começar
  selector:
    matchLabels:
      app: newApp
  template:
    metadata:
      labels:
        app: newApp
    spec:
      containers:
      - name: newApp-container
        image: manaramarcelo/newApp:{{tag}} 
        ports:
        - containerPort: 8000