apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-app-deployment
  labels:
    app: nova-app
spec:
  replicas: 1 # Apenas 1 réplica para começar
  selector:
    matchLabels:
      app: nova-app
  template:
    metadata:
      labels:
        app: nova-app
    spec:
      containers:
      - name: nova-app-container
        image: manaramarcelo/nova-app:{{tag}} # <--- ATENÇÃO: Use seu username do Docker Hub
        ports:
        - containerPort: 8000