apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
  labels:
    app: new-app
spec:
  replicas: 1 # Apenas 1 réplica para começar
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
      containers:
      - name: new-app-container
        image: manaramarcelo/new-app:{{tag}} 
        ports:
        - containerPort: 8000